// Code generated by ogen, DO NOT EDIT.

package publicoas

// OperationName is the ogen operation name
type OperationName = string

const (
	GetCurrentWeatherOperation OperationName = "GetCurrentWeather"
	GetHealthzOperation        OperationName = "GetHealthz"
)
