// Code generated by ogen, DO NOT EDIT.

package publicoas

import (
	"fmt"
	"time"
)

func (s *DefaultErrorStatusCodeWithHeaders) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/CurrentWeatherResponse
type CurrentWeatherResponse struct {
	Provider     string    `json:"provider"`
	Location     string    `json:"location"`
	Condition    string    `json:"condition"`
	TemperatureC float64   `json:"temperatureC"`
	ObservedAt   time.Time `json:"observedAt"`
}

// GetProvider returns the value of Provider.
func (s *CurrentWeatherResponse) GetProvider() string {
	return s.Provider
}

// GetLocation returns the value of Location.
func (s *CurrentWeatherResponse) GetLocation() string {
	return s.Location
}

// GetCondition returns the value of Condition.
func (s *CurrentWeatherResponse) GetCondition() string {
	return s.Condition
}

// GetTemperatureC returns the value of TemperatureC.
func (s *CurrentWeatherResponse) GetTemperatureC() float64 {
	return s.TemperatureC
}

// GetObservedAt returns the value of ObservedAt.
func (s *CurrentWeatherResponse) GetObservedAt() time.Time {
	return s.ObservedAt
}

// SetProvider sets the value of Provider.
func (s *CurrentWeatherResponse) SetProvider(val string) {
	s.Provider = val
}

// SetLocation sets the value of Location.
func (s *CurrentWeatherResponse) SetLocation(val string) {
	s.Location = val
}

// SetCondition sets the value of Condition.
func (s *CurrentWeatherResponse) SetCondition(val string) {
	s.Condition = val
}

// SetTemperatureC sets the value of TemperatureC.
func (s *CurrentWeatherResponse) SetTemperatureC(val float64) {
	s.TemperatureC = val
}

// SetObservedAt sets the value of ObservedAt.
func (s *CurrentWeatherResponse) SetObservedAt(val time.Time) {
	s.ObservedAt = val
}

// CurrentWeatherResponseHeaders wraps CurrentWeatherResponse with response headers.
type CurrentWeatherResponseHeaders struct {
	XRequestID OptString
	Response   CurrentWeatherResponse
}

// GetXRequestID returns the value of XRequestID.
func (s *CurrentWeatherResponseHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *CurrentWeatherResponseHeaders) GetResponse() CurrentWeatherResponse {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *CurrentWeatherResponseHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *CurrentWeatherResponseHeaders) SetResponse(val CurrentWeatherResponse) {
	s.Response = val
}

// DefaultErrorStatusCodeWithHeaders wraps ErrorResponse with status code and response headers.
type DefaultErrorStatusCodeWithHeaders struct {
	StatusCode int
	XRequestID OptString
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *DefaultErrorStatusCodeWithHeaders) GetStatusCode() int {
	return s.StatusCode
}

// GetXRequestID returns the value of XRequestID.
func (s *DefaultErrorStatusCodeWithHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *DefaultErrorStatusCodeWithHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *DefaultErrorStatusCodeWithHeaders) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetXRequestID sets the value of XRequestID.
func (s *DefaultErrorStatusCodeWithHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *DefaultErrorStatusCodeWithHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Code      string    `json:"code"`
	Message   string    `json:"message"`
	RequestId OptString `json:"requestId"`
}

// GetCode returns the value of Code.
func (s *ErrorResponse) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// GetRequestId returns the value of RequestId.
func (s *ErrorResponse) GetRequestId() OptString {
	return s.RequestId
}

// SetCode sets the value of Code.
func (s *ErrorResponse) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

// SetRequestId sets the value of RequestId.
func (s *ErrorResponse) SetRequestId(val OptString) {
	s.RequestId = val
}

// Ref: #/components/schemas/HealthResponse
type HealthResponse struct {
	Status string `json:"status"`
}

// GetStatus returns the value of Status.
func (s *HealthResponse) GetStatus() string {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *HealthResponse) SetStatus(val string) {
	s.Status = val
}

// HealthResponseHeaders wraps HealthResponse with response headers.
type HealthResponseHeaders struct {
	XRequestID OptString
	Response   HealthResponse
}

// GetXRequestID returns the value of XRequestID.
func (s *HealthResponseHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *HealthResponseHeaders) GetResponse() HealthResponse {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *HealthResponseHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *HealthResponseHeaders) SetResponse(val HealthResponse) {
	s.Response = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}
