// Code generated by ogen, DO NOT EDIT.

package publicoas

import (
	"net/http"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetCurrentWeatherParams is parameters of getCurrentWeather operation.
type GetCurrentWeatherParams struct {
	Location string
}

func unpackGetCurrentWeatherParams(packed middleware.Parameters) (params GetCurrentWeatherParams) {
	{
		key := middleware.ParameterKey{
			Name: "location",
			In:   "query",
		}
		params.Location = packed[key].(string)
	}
	return params
}

func decodeGetCurrentWeatherParams(args [0]string, argsEscaped bool, r *http.Request) (params GetCurrentWeatherParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: location.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "location",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Location = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.Location)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "location",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
