// Code generated by ogen, DO NOT EDIT.

package publicoas

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateNoteOperation OperationName = "CreateNote"
	DeleteNoteOperation OperationName = "DeleteNote"
	GetHealthzOperation OperationName = "GetHealthz"
	GetNoteOperation    OperationName = "GetNote"
	ListNotesOperation  OperationName = "ListNotes"
	UpdateNoteOperation OperationName = "UpdateNote"
)
