// Code generated by ogen, DO NOT EDIT.
package publicoas

type CreateNoteRes interface {
	createNoteRes()
}

type DeleteNoteRes interface {
	deleteNoteRes()
}

type GetHealthzRes interface {
	getHealthzRes()
}

type GetNoteRes interface {
	getNoteRes()
}

type ListNotesRes interface {
	listNotesRes()
}

type UpdateNoteRes interface {
	updateNoteRes()
}
