// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health.sql

package dbsqlc

import (
	"context"
)

const databasePing = `-- name: DatabasePing :one
SELECT 1 AS ok
`

func (q *Queries) DatabasePing(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, databasePing)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
