// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: http_client_audit.sql

package dbsqlc

import (
	"context"
)

const insertHTTPClientAudit = `-- name: InsertHTTPClientAudit :exec
INSERT INTO http_client_audit (
    client,
    operation,
    method,
    path,
    query,
    host,
    scheme,
    status_code,
    duration_ms,
    request_size_bytes,
    response_size_bytes,
    request_headers,
    response_headers,
    request_body,
    response_body,
    request_body_truncated,
    response_body_truncated,
    error_kind,
    error_message,
    trace_id,
    span_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21
)
`

type InsertHTTPClientAuditParams struct {
	Client                string `json:"client"`
	Operation             string `json:"operation"`
	Method                string `json:"method"`
	Path                  string `json:"path"`
	Query                 string `json:"query"`
	Host                  string `json:"host"`
	Scheme                string `json:"scheme"`
	StatusCode            int32  `json:"status_code"`
	DurationMs            int64  `json:"duration_ms"`
	RequestSizeBytes      int64  `json:"request_size_bytes"`
	ResponseSizeBytes     int64  `json:"response_size_bytes"`
	RequestHeaders        []byte `json:"request_headers"`
	ResponseHeaders       []byte `json:"response_headers"`
	RequestBody           []byte `json:"request_body"`
	ResponseBody          []byte `json:"response_body"`
	RequestBodyTruncated  bool   `json:"request_body_truncated"`
	ResponseBodyTruncated bool   `json:"response_body_truncated"`
	ErrorKind             string `json:"error_kind"`
	ErrorMessage          string `json:"error_message"`
	TraceID               string `json:"trace_id"`
	SpanID                string `json:"span_id"`
}

func (q *Queries) InsertHTTPClientAudit(ctx context.Context, arg InsertHTTPClientAuditParams) error {
	_, err := q.db.Exec(ctx, insertHTTPClientAudit,
		arg.Client,
		arg.Operation,
		arg.Method,
		arg.Path,
		arg.Query,
		arg.Host,
		arg.Scheme,
		arg.StatusCode,
		arg.DurationMs,
		arg.RequestSizeBytes,
		arg.ResponseSizeBytes,
		arg.RequestHeaders,
		arg.ResponseHeaders,
		arg.RequestBody,
		arg.ResponseBody,
		arg.RequestBodyTruncated,
		arg.ResponseBodyTruncated,
		arg.ErrorKind,
		arg.ErrorMessage,
		arg.TraceID,
		arg.SpanID,
	)
	return err
}
