// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsqlc

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type HttpClientAudit struct {
	ID                    int64              `json:"id"`
	Client                string             `json:"client"`
	Operation             string             `json:"operation"`
	Method                string             `json:"method"`
	Path                  string             `json:"path"`
	Query                 string             `json:"query"`
	Host                  string             `json:"host"`
	Scheme                string             `json:"scheme"`
	StatusCode            int32              `json:"status_code"`
	DurationMs            int64              `json:"duration_ms"`
	RequestSizeBytes      int64              `json:"request_size_bytes"`
	ResponseSizeBytes     int64              `json:"response_size_bytes"`
	RequestHeaders        []byte             `json:"request_headers"`
	ResponseHeaders       []byte             `json:"response_headers"`
	RequestBody           []byte             `json:"request_body"`
	ResponseBody          []byte             `json:"response_body"`
	RequestBodyTruncated  bool               `json:"request_body_truncated"`
	ResponseBodyTruncated bool               `json:"response_body_truncated"`
	ErrorKind             string             `json:"error_kind"`
	ErrorMessage          string             `json:"error_message"`
	RequestID             string             `json:"request_id"`
	TraceID               string             `json:"trace_id"`
	SpanID                string             `json:"span_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type HttpRequestAudit struct {
	ID                    int64              `json:"id"`
	Server                string             `json:"server"`
	Route                 string             `json:"route"`
	Method                string             `json:"method"`
	Path                  string             `json:"path"`
	Query                 string             `json:"query"`
	Host                  string             `json:"host"`
	Scheme                string             `json:"scheme"`
	Proto                 string             `json:"proto"`
	StatusCode            int32              `json:"status_code"`
	DurationMs            int64              `json:"duration_ms"`
	RequestSizeBytes      int64              `json:"request_size_bytes"`
	ResponseSizeBytes     int64              `json:"response_size_bytes"`
	RemoteAddr            string             `json:"remote_addr"`
	ClientIp              *netip.Addr        `json:"client_ip"`
	UserAgent             string             `json:"user_agent"`
	RequestHeaders        []byte             `json:"request_headers"`
	ResponseHeaders       []byte             `json:"response_headers"`
	RequestBody           []byte             `json:"request_body"`
	ResponseBody          []byte             `json:"response_body"`
	RequestBodyTruncated  bool               `json:"request_body_truncated"`
	ResponseBodyTruncated bool               `json:"response_body_truncated"`
	RequestID             string             `json:"request_id"`
	TraceID               string             `json:"trace_id"`
	SpanID                string             `json:"span_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type Note struct {
	ID                  uuid.UUID          `json:"id"`
	Title               string             `json:"title"`
	Body                string             `json:"body"`
	LocationQuery       string             `json:"location_query"`
	ResolvedLocation    string             `json:"resolved_location"`
	WeatherProvider     string             `json:"weather_provider"`
	WeatherCondition    string             `json:"weather_condition"`
	WeatherTemperatureC float64            `json:"weather_temperature_c"`
	WeatherObservedAt   pgtype.Timestamptz `json:"weather_observed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
