// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notes.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes
WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNote = `-- name: GetNote :one
SELECT id, title, body, location_query, resolved_location, weather_provider, weather_condition, weather_temperature_c, weather_observed_at, created_at, updated_at
FROM notes
WHERE id = $1
`

func (q *Queries) GetNote(ctx context.Context, id uuid.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.LocationQuery,
		&i.ResolvedLocation,
		&i.WeatherProvider,
		&i.WeatherCondition,
		&i.WeatherTemperatureC,
		&i.WeatherObservedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertNote = `-- name: InsertNote :one
INSERT INTO notes (
    title,
    body,
    location_query,
    resolved_location,
    weather_provider,
    weather_condition,
    weather_temperature_c,
    weather_observed_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, created_at, updated_at
`

type InsertNoteParams struct {
	Title               string             `json:"title"`
	Body                string             `json:"body"`
	LocationQuery       string             `json:"location_query"`
	ResolvedLocation    string             `json:"resolved_location"`
	WeatherProvider     string             `json:"weather_provider"`
	WeatherCondition    string             `json:"weather_condition"`
	WeatherTemperatureC float64            `json:"weather_temperature_c"`
	WeatherObservedAt   pgtype.Timestamptz `json:"weather_observed_at"`
}

type InsertNoteRow struct {
	ID        uuid.UUID          `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) InsertNote(ctx context.Context, arg InsertNoteParams) (InsertNoteRow, error) {
	row := q.db.QueryRow(ctx, insertNote,
		arg.Title,
		arg.Body,
		arg.LocationQuery,
		arg.ResolvedLocation,
		arg.WeatherProvider,
		arg.WeatherCondition,
		arg.WeatherTemperatureC,
		arg.WeatherObservedAt,
	)
	var i InsertNoteRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const listNotesPage = `-- name: ListNotesPage :many
SELECT id, title, body, location_query, resolved_location, weather_provider, weather_condition, weather_temperature_c, weather_observed_at, created_at, updated_at
FROM notes
WHERE (
    $1::timestamptz IS NULL
    OR (created_at, id) < ($1::timestamptz, $2::uuid)
)
ORDER BY created_at DESC, id DESC
LIMIT $3::int
`

type ListNotesPageParams struct {
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        uuid.UUID          `json:"cursor_id"`
	LimitCount      int32              `json:"limit_count"`
}

func (q *Queries) ListNotesPage(ctx context.Context, arg ListNotesPageParams) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotesPage, arg.CursorCreatedAt, arg.CursorID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Body,
			&i.LocationQuery,
			&i.ResolvedLocation,
			&i.WeatherProvider,
			&i.WeatherCondition,
			&i.WeatherTemperatureC,
			&i.WeatherObservedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET
    title = $1,
    body = $2,
    location_query = $3,
    resolved_location = $4,
    weather_provider = $5,
    weather_condition = $6,
    weather_temperature_c = $7,
    weather_observed_at = $8,
    updated_at = NOW()
WHERE id = $9
RETURNING updated_at
`

type UpdateNoteParams struct {
	Title               string             `json:"title"`
	Body                string             `json:"body"`
	LocationQuery       string             `json:"location_query"`
	ResolvedLocation    string             `json:"resolved_location"`
	WeatherProvider     string             `json:"weather_provider"`
	WeatherCondition    string             `json:"weather_condition"`
	WeatherTemperatureC float64            `json:"weather_temperature_c"`
	WeatherObservedAt   pgtype.Timestamptz `json:"weather_observed_at"`
	ID                  uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.Title,
		arg.Body,
		arg.LocationQuery,
		arg.ResolvedLocation,
		arg.WeatherProvider,
		arg.WeatherCondition,
		arg.WeatherTemperatureC,
		arg.WeatherObservedAt,
		arg.ID,
	)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}
