// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbsqlc

import (
	"context"
)

type Querier interface {
	DatabasePing(ctx context.Context) (int32, error)
	InsertHTTPClientAudit(ctx context.Context, arg InsertHTTPClientAuditParams) error
	InsertHTTPRequestAudit(ctx context.Context, arg InsertHTTPRequestAuditParams) error
}

var _ Querier = (*Queries)(nil)
