// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: request_audit.sql

package dbsqlc

import (
	"context"
	"net/netip"
)

const insertHTTPRequestAudit = `-- name: InsertHTTPRequestAudit :exec
INSERT INTO http_request_audit (
    server,
    route,
    method,
    path,
    query,
    host,
    scheme,
    proto,
    status_code,
    duration_ms,
    request_size_bytes,
    response_size_bytes,
    remote_addr,
    client_ip,
    user_agent,
    request_headers,
    response_headers,
    request_body,
    response_body,
    request_body_truncated,
    response_body_truncated,
    trace_id,
    span_id
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23
)
`

type InsertHTTPRequestAuditParams struct {
	Server                string      `json:"server"`
	Route                 string      `json:"route"`
	Method                string      `json:"method"`
	Path                  string      `json:"path"`
	Query                 string      `json:"query"`
	Host                  string      `json:"host"`
	Scheme                string      `json:"scheme"`
	Proto                 string      `json:"proto"`
	StatusCode            int32       `json:"status_code"`
	DurationMs            int64       `json:"duration_ms"`
	RequestSizeBytes      int64       `json:"request_size_bytes"`
	ResponseSizeBytes     int64       `json:"response_size_bytes"`
	RemoteAddr            string      `json:"remote_addr"`
	ClientIp              *netip.Addr `json:"client_ip"`
	UserAgent             string      `json:"user_agent"`
	RequestHeaders        []byte      `json:"request_headers"`
	ResponseHeaders       []byte      `json:"response_headers"`
	RequestBody           []byte      `json:"request_body"`
	ResponseBody          []byte      `json:"response_body"`
	RequestBodyTruncated  bool        `json:"request_body_truncated"`
	ResponseBodyTruncated bool        `json:"response_body_truncated"`
	TraceID               string      `json:"trace_id"`
	SpanID                string      `json:"span_id"`
}

func (q *Queries) InsertHTTPRequestAudit(ctx context.Context, arg InsertHTTPRequestAuditParams) error {
	_, err := q.db.Exec(ctx, insertHTTPRequestAudit,
		arg.Server,
		arg.Route,
		arg.Method,
		arg.Path,
		arg.Query,
		arg.Host,
		arg.Scheme,
		arg.Proto,
		arg.StatusCode,
		arg.DurationMs,
		arg.RequestSizeBytes,
		arg.ResponseSizeBytes,
		arg.RemoteAddr,
		arg.ClientIp,
		arg.UserAgent,
		arg.RequestHeaders,
		arg.ResponseHeaders,
		arg.RequestBody,
		arg.ResponseBody,
		arg.RequestBodyTruncated,
		arg.ResponseBodyTruncated,
		arg.TraceID,
		arg.SpanID,
	)
	return err
}
