// Code generated by ogen, DO NOT EDIT.

package infraoas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	InfraHandler
	// NewError creates *DefaultErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *DefaultErrorStatusCode
}

// InfraHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Infra
type InfraHandler interface {
	// GetHealthz implements getHealthz operation.
	//
	// Service health summary endpoint.
	//
	// GET /healthz
	GetHealthz(ctx context.Context) (*HealthResponse, error)
	// GetLivez implements getLivez operation.
	//
	// Liveness probe endpoint.
	//
	// GET /livez
	GetLivez(ctx context.Context) (*ProbeResponse, error)
	// GetReadyz implements getReadyz operation.
	//
	// Readiness probe endpoint.
	//
	// GET /readyz
	GetReadyz(ctx context.Context) (*ProbeResponse, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
