// Code generated by ogen, DO NOT EDIT.

package infraoas

// OperationName is the ogen operation name
type OperationName = string

const (
	GetHealthzOperation OperationName = "GetHealthz"
	GetLivezOperation   OperationName = "GetLivez"
	GetReadyzOperation  OperationName = "GetReadyz"
)
