// Code generated by ogen, DO NOT EDIT.

package infraoas

import (
	"fmt"
)

func (s *DefaultErrorStatusCodeWithHeaders) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// DefaultErrorStatusCodeWithHeaders wraps ErrorResponse with status code and response headers.
type DefaultErrorStatusCodeWithHeaders struct {
	StatusCode int
	XRequestID OptString
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *DefaultErrorStatusCodeWithHeaders) GetStatusCode() int {
	return s.StatusCode
}

// GetXRequestID returns the value of XRequestID.
func (s *DefaultErrorStatusCodeWithHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *DefaultErrorStatusCodeWithHeaders) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *DefaultErrorStatusCodeWithHeaders) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetXRequestID sets the value of XRequestID.
func (s *DefaultErrorStatusCodeWithHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *DefaultErrorStatusCodeWithHeaders) SetResponse(val ErrorResponse) {
	s.Response = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Code      string    `json:"code"`
	Message   string    `json:"message"`
	RequestId OptString `json:"requestId"`
}

// GetCode returns the value of Code.
func (s *ErrorResponse) GetCode() string {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// GetRequestId returns the value of RequestId.
func (s *ErrorResponse) GetRequestId() OptString {
	return s.RequestId
}

// SetCode sets the value of Code.
func (s *ErrorResponse) SetCode(val string) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

// SetRequestId sets the value of RequestId.
func (s *ErrorResponse) SetRequestId(val OptString) {
	s.RequestId = val
}

// Ref: #/components/schemas/HealthResponse
type HealthResponse struct {
	Status      string `json:"status"`
	Version     string `json:"version"`
	Timestamp   string `json:"timestamp"`
	Environment string `json:"environment"`
}

// GetStatus returns the value of Status.
func (s *HealthResponse) GetStatus() string {
	return s.Status
}

// GetVersion returns the value of Version.
func (s *HealthResponse) GetVersion() string {
	return s.Version
}

// GetTimestamp returns the value of Timestamp.
func (s *HealthResponse) GetTimestamp() string {
	return s.Timestamp
}

// GetEnvironment returns the value of Environment.
func (s *HealthResponse) GetEnvironment() string {
	return s.Environment
}

// SetStatus sets the value of Status.
func (s *HealthResponse) SetStatus(val string) {
	s.Status = val
}

// SetVersion sets the value of Version.
func (s *HealthResponse) SetVersion(val string) {
	s.Version = val
}

// SetTimestamp sets the value of Timestamp.
func (s *HealthResponse) SetTimestamp(val string) {
	s.Timestamp = val
}

// SetEnvironment sets the value of Environment.
func (s *HealthResponse) SetEnvironment(val string) {
	s.Environment = val
}

// HealthResponseHeaders wraps HealthResponse with response headers.
type HealthResponseHeaders struct {
	XRequestID OptString
	Response   HealthResponse
}

// GetXRequestID returns the value of XRequestID.
func (s *HealthResponseHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *HealthResponseHeaders) GetResponse() HealthResponse {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *HealthResponseHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *HealthResponseHeaders) SetResponse(val HealthResponse) {
	s.Response = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/ProbeResponse
type ProbeResponse struct {
	Status string `json:"status"`
}

// GetStatus returns the value of Status.
func (s *ProbeResponse) GetStatus() string {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *ProbeResponse) SetStatus(val string) {
	s.Status = val
}

// ProbeResponseHeaders wraps ProbeResponse with response headers.
type ProbeResponseHeaders struct {
	XRequestID OptString
	Response   ProbeResponse
}

// GetXRequestID returns the value of XRequestID.
func (s *ProbeResponseHeaders) GetXRequestID() OptString {
	return s.XRequestID
}

// GetResponse returns the value of Response.
func (s *ProbeResponseHeaders) GetResponse() ProbeResponse {
	return s.Response
}

// SetXRequestID sets the value of XRequestID.
func (s *ProbeResponseHeaders) SetXRequestID(val OptString) {
	s.XRequestID = val
}

// SetResponse sets the value of Response.
func (s *ProbeResponseHeaders) SetResponse(val ProbeResponse) {
	s.Response = val
}
