// Code generated by ogen, DO NOT EDIT.

package weatheroas

// OperationName is the ogen operation name
type OperationName = string

const (
	GetCurrentWeatherOperation OperationName = "GetCurrentWeather"
)
