// Code generated by ogen, DO NOT EDIT.

package weatheroas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	WeatherHandler
	// NewError creates *DefaultErrorStatusCodeWithHeaders from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *DefaultErrorStatusCodeWithHeaders
}

// WeatherHandler handles operations described by OpenAPI v3 specification.
//
// x-ogen-operation-group: Weather
type WeatherHandler interface {
	// GetCurrentWeather implements getCurrentWeather operation.
	//
	// Current weather for a location.
	//
	// GET /weather/current
	GetCurrentWeather(ctx context.Context, params GetCurrentWeatherParams) (GetCurrentWeatherRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
