name: Quality
on:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Setup just
        uses: taiki-e/install-action@d8d7bd3d6a8d4366c7cb83df6330ff0d6cd77c2e # just
      - name: Cache local tool binaries
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: .bin
          key: ${{ runner.os }}-bin-${{ hashFiles('justfile') }}
      - name: Run checks
        run: just ci
